[package]
name = "msxide"
version = "0.1.0"
edition = "2026"

[build]
src = "src/main.c-"
compiler = "cc"
cflags = "-std=gnu99 -Wall -Wextra -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600"
ldflags = "-lncursesw -ltinfo"
