[package]
name = "small"
version = "0.2.0"
edition = "2026"

[build]
src = "src/main.c-"
compiler = "clang"
cflags = "-std=gnu99 -Wall -Wextra -flto=thin"
ldflags = ""
bare = true
strip = true
strip_sections = true
